apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  POSTGRES_DB: "auth_db"
  POSTGRES_URL: "jdbc:postgresql://postgres:5432/auth_db"
  POSTGRES_USER: "user"
  KAFKA_BOOTSTRAP: "kafka:9092"
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "task-realm"
  KEYCLOAK_RESOURCE: "task-client"