apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: dev
data:
  task-realm-realm.json: |
    {
      "id": "task-realm",
      "realm": "task-realm",
      "enabled": true,
      "registrationAllowed": true,
      "clients": [
        {
          "clientId": "task-client",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "fullScopeAllowed": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "email": "test@test.com",
          "credentials": [
            {
              "type": "password",
              "value": "password"
            }
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.6.0
          command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-volume
          configMap:
            name: keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: dev
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080