apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: search:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: dev
spec:
  selector:
    app: search-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: management
      port: 8083
      targetPort: 8083