apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vt-storage-pvc
  namespace: dev
  labels:
    app: victoria-traces
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-traces
  namespace: dev
  labels:
    app: victoria-traces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-traces
  template:
    metadata:
      labels:
        app: victoria-traces
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: victoria-traces
          image: victoriametrics/victoria-traces:v0.10.0
          imagePullPolicy: IfNotPresent
          args:
            - "--storageDataPath=/storage"
            - "--retentionPeriod=1d"
          ports:
            - name: http
              containerPort: 10428
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          volumeMounts:
            - name: storage-volume
              mountPath: /storage
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: vt-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-traces
  namespace: dev
  labels:
    app: victoria-traces
spec:
  selector:
    app: victoria-traces
  ports:
    - name: http
      port: 10428
      targetPort: http
      protocol: TCP
  type: ClusterIP