server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/task-realm

management:
  server:
    port: 8090

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  opentelemetry:
    resource-attributes:
      service.name: gateway
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/logs

  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
    prometheus:
      enabled: true

logging:
  structured:
    format:
      console: ecs
  level:
    org.springframework.cloud.gateway: INFO
    io.micrometer.registry.otlp: WARN
    io.opentelemetry.exporter: WARN