server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/task-realm
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 10
        batch.size: 16384
      acks: all
    admin:
      auto-create-topics: true
    consumer:
      group-id: tasks-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.kafka: INFO

app:
  kafka:
    topics:
      task-flow: task-flow
      task-stream: task-stream
      status-changed: status-changed
      executor-assigned: executor-assigned