server:
  port: 8080

spring:
  application:
    name: app-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: false
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        linger.ms: 10
        batch.size: 16384
        acks: all
    admin:
      auto-create-topics: true
    consumer:
      group-id: tasks-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

app:
  kafka:
    topics:
      task-flow: task-flow
      task-stream: task-stream

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector.dev.svc.cluster.local:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://otel-collector.dev.svc.cluster.local:4318

  otlp:
    metrics:
      export:
        url: http://otel-collector.dev.svc.cluster.local:4318/v1/metrics

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

logging:
  structured:
    format:
      console: ecs
  opentelemetry:
    enabled: true

