server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        linger.ms: 10
        batch.size: 16384
      acks: all

    admin:
      auto-create-topics: true

    consumer:
      group-id: tasks-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/task-realm

keycloak:
  auth-server-url: http://keycloak:8080
  realm: task-realm
  resource: task-client
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

auth:
  kafka:
    topics:
      user-stream: user-stream
      user-flow: user-flow

management:
  server:
    port: 8081

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  opentelemetry:
    resource-attributes:
      service.name: auth-service
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/logs

  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
    prometheus:
      enabled: true

logging:
  structured:
    format:
      console: ecs
  level:
    io.micrometer.registry.otlp: WARN
    io.opentelemetry.exporter: WARN