--liquibase formatted sql

--changeset developer:1
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    user_id UUID NOT NULL UNIQUE
);

--changeset developer:2
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    user_id UUID,
    created_at TIMESTAMP NOT NULL
);

--changeset developer:3
CREATE INDEX idx_tasks_user_id ON tasks(user_id);

--changeset developer:4
CREATE TABLE search_schema (

);